### ISSUE TITLE
API설계하기

### ISSUE THREAD

**Issue by cpfl300** [cpfl300/2014_HARU#3]

**Comment by cocagolau** [comment]
[이슈 뷰]
- 이슈의 내용을 요청
  - 사진(1~3개), 기사제목, 신문사, 섹션, 우선순위, 읽음 여부
- 이슈에 포함된 기사 읽음 여부 요청
- 댓글 입력 요청
- 댓글 추가 요청
- 댓글 리스트 요청
- 댓글 삭제 요청
- 댓글 수정 요청

**Comment by cocagolau** [comment]
[기사 뷰]
- 기사 내용 요청
- 기사 읽음 저장 요청

**Comment by cocagolau** [comment]
[메인 뷰]
