### ISSUE TITLE
freemaker 공부하기

### ISSUE THREAD

**Issue by cpfl300** [cpfl300/2014_HARU#71]

**Comment by cocagolau** [comment]
템플릿 엔진에 대하여

템플릿 엔진 비교
http://www.todaysoftmag.com/article/907/template-engines-for-java-web-development

freemarker를 spring에서 사용시 의존 라이브러리
http://stackoverflow.com/questions/17629786/how-do-i-add-freemarker-support-to-a-spring-mvc-webapp-dependency-issue

사용방법
http://freemarker.org/docs/dgui_quickstart_basics.html

eclipse에서 ftl파일을 html 파일처럼 사용하는 방법
http://stackoverflow.com/questions/4044414/format-freemarker-files-in-eclipse

**Comment by cocagolau** [comment]
월요일 스터디 예정
